### ISSUE TITLE
Unable to download reddit_vectors model

### ISSUE THREAD

**Issue by boscoraju** [explosion/sense2vec#15]
Hi @honnibal ,

I am getting the following error when I execute: 
$ python -m sense2vec.download

File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/boscoraju/src/sense2vec/sense2vec/download.py", line 38, in <module>
    plac.call(main)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(_(args + varargs + extraopts), *_kwargs)
  File "/Users/boscoraju/src/sense2vec/sense2vec/download.py", line 26, in main
    package = sputnik.install(about.__title__, about.**version**, about.**default_model**)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sputnik/**init**.py", line 37, in install
    index.update()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sputnik/index.py", line 84, in update
    index = json.load(session.open(request, 'utf8'))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sputnik/session.py", line 43, in open
    r = self.opener.open(request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)>

Looks like it is unable to make a connection. Could you point me to right direction?

Thank you.

**Comment by g3rm4nf0x** [comment]
Unfortunately, I also face the following error while executing the same command:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/parsi/python/src/sense2vec/sense2vec/download.py", line 38, in <module>
    plac.call(main)
  File "/usr/local/lib/python2.7/dist-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python2.7/dist-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/parsi/python/src/sense2vec/sense2vec/download.py", line 26, in main
    package = sputnik.install(about.__title__, about.__version__, about.__default_model__)
  File "/usr/local/lib/python2.7/dist-packages/sputnik/__init__.py", line 44, in install
    archive = cache.fetch(package_name)
  File "/usr/local/lib/python2.7/dist-packages/sputnik/cache.py", line 57, in fetch
    package = self.get(package_string)
  File "/usr/local/lib/python2.7/dist-packages/sputnik/package_list.py", line 57, in get
    raise PackageNotFoundException(package_string)
sputnik.package_list.PackageNotFoundException: reddit_vectors>=1.1.0,<1.2.0
```

**Comment by elyase** [comment]
If you have a copy of the models from a previous install you can do:
```python
from sense2vec.vectors import VectorMap

vector_map = VectorMap(128)
vector_map.load('/Users/yaser/.spacy/models/reddit_vectors-1.1.0/')
```

**Comment by boscoraju** [comment]
@elyase Unfortunately, I don't have a copy of the previous version.

**Comment by elyase** [comment]
I assume you don't want to train you own vectors? In that case I could upload a copy for you (~700mb).

**Comment by g3rm4nf0x** [comment]
That would be really helpful :)

**Comment by elyase** [comment]
Here you go: 

https://dl.dropboxusercontent.com/u/2393585/reddit_vectors-1.1.0.zip

you need to unzip it, before calling `vector_map.load`.

**Comment by boscoraju** [comment]
Cheers @elyase

**Comment by bahadorkh** [comment]
@elyase : I successfully loaded the model you provided, through Python shell, yet the problem persists when I try to update to download the latest model.

**Comment by syllog1sm** [comment]
Thanks for the upload @elyase , and apologies for the delay. I've now gotten the model hosted again on sputnik. Still having SSL problems, so the `sense2vec.download` script isn't working properly. This is, though:

```sputnik --name sense2vec --repository-url http://index.spacy.io install reddit_vectors```

**Comment by sp258** [comment]
@syllog1sm thank you very much for all of your contributions. Your nlp libraries are great, and I am excited to try out sense2vec. I unfortunately can't get it properly installed. 

I've tried installing through sputnik, which runs fine, but I still get the errors when I try to run the code provided in the "usage" section in a file named test.py. I'd appreciate any help you could provide.

Traceback (most recent call last):
  File "test.py", line 2, in <module>
    model = sense2vec.load()
  File ".../sense2vec/sense2vec/__init__.py", line 6, in load
    package = util.get_package_by_name(name, via=via)
  File ".../sense2vec/sense2vec/util.py", line 20, in get_package_by_name
    raise RuntimeError("Model not installed. Please run 'python -m "
RuntimeError: Model not installed. Please run 'python -m sense2vec.download' to install latest compatible model.

**Comment by lahloug** [comment]
Hi, when I run the sputnik command  I have this error. I think it is because the reddit_vectors are no longer available. Is it possible to have another copy @elyase  ? 


Isputnik --name sense2vec --repository-url http://index.spacy.io install reddit_vectors
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/glahlou/v3/bin/sputnik", line 11, in <module>
    sys.exit(main())
  File "/home/glahlou/v3/lib/python3.5/site-packages/sputnik/__main__.py", line 12, in main
    args.run(args)
  File "/home/glahlou/v3/lib/python3.5/site-packages/sputnik/cli.py", line 45, in run
    repository_url=args.repository_url)
  File "/home/glahlou/v3/lib/python3.5/site-packages/sputnik/__init__.py", line 37, in install
    index.update()
  File "/home/glahlou/v3/lib/python3.5/site-packages/sputnik/index.py", line 84, in update
    index = json.load(session.open(request, 'utf8'))
  File "/home/glahlou/v3/lib/python3.5/site-packages/sputnik/session.py", line 43, in open
    r = self.opener.open(request)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
Exception ignored in: <bound method Session.__del__ of <sputnik.session.Session object at 0x7fcb7aa63940>>
Traceback (most recent call last):
  File "/home/glahlou/v3/lib/python3.5/site-packages/sputnik/session.py", line 58, in __del__
  File "/usr/lib/python3.5/http/cookiejar.py", line 2070, in save
NameError: name 'open' is not defined

**Comment by adeokar** [comment]
Is the reddit_vectors model still available for download? If so, can someone please provide details on how to do so? Thank you.

**Comment by patrickleet** [comment]
```
sputnik --name sense2vec --repository-url http://index.spacy.io install reddit_vectors
```
used to work in our docker image, but it's been a few months and now running it results in an error:

```
Traceback (most recent call last):
  File "/usr/local/bin/sputnik", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/sputnik/__main__.py", line 12, in main
    args.run(args)
  File "/usr/local/lib/python3.5/dist-packages/sputnik/cli.py", line 45, in run
    repository_url=args.repository_url)
  File "/usr/local/lib/python3.5/dist-packages/sputnik/__init__.py", line 44, in install
    archive = cache.fetch(package_name)
  File "/usr/local/lib/python3.5/dist-packages/sputnik/cache.py", line 67, in fetch
    checksum_header=util.s3_header('md5'))
  File "/usr/local/lib/python3.5/dist-packages/sputnik/uget.py", line 219, in download
    write_func=write)
  File "/usr/local/lib/python3.5/dist-packages/sputnik/uget.py", line 187, in read_request
    assert bytes_read == total_size
AssertionError
```

**Comment by patrickleet** [comment]
@syllog1sm ^

Based on your comment it looks like it was you who hosted it.

Any ideas about the error?

**Comment by TedYav** [comment]
@patrickleet Hey all I was having an issue with this too. There's an SSL issue that doesn't seem surmountable, however a "hack" to fix it is to patch `sputnik` to disable SSL verification temporarily.

If you edit `session.py` in your Sputnik library folder you can disable SSL verification by amending your imports as follows. For me this file was located at:

`/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sputnik/session.py`

`import ssl` and
`from urllib.request import Request, build_opener, HTTPRedirectHandler, HTTPCookieProcessor, HTTPSHandler` (adding `HTTPSHandler`)

Then in `init` modify the code to read as follows before the `self.opener = build_opener`...line

```
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE

        self.opener = build_opener(
            HTTPSHandler(context=ctx),
            HTTPRedirectHandler(),
            HTTPCookieProcessor(self.cookie_jar))
```

You may want to revert after for safety.

**Comment by MotorCityCobra** [comment]
Hello, anybody?  
I'm having trouble using the reddit vectors after downloading. I can't find them.  
After the vectors are downloaded I enter a '$locate reddit' and nothing relating to the vectors is located. Does something need to be unzipped and installed somewhere?

    $ sputnik --name sense2vec --repository-url http://index.spacy.io install reddit_vectors
    Continue downloading...
    Downloaded 560.90MB 100.00% 0.21MB/s eta 1s               
    archive.gz checksum/md5 OK
    INFO:sputnik.pool:install reddit_vectors-1.1.0
    $

If I enter  

    sputnik --name sense2vec --repository-url http://index.spacy.io install reddit_vectors  

into the command line again nothing happens.
