### ISSUE TITLE
Unable to load model 

### ISSUE THREAD

**Issue by reneg117** [explosion/sense2vec#18]
When I tried to load the model via "model = sense2vec.load()" I get the following error:

RuntimeError("Model not installed. Please run 'python -m "
RuntimeError: Model not installed. Please run 'python -m sense2vec.download' to install latest compatible model.

Then I tried to execute the command "'python -m sense2vec.download" and I got another error:

File "C:\Users\rg\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\rg\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\rg\src\sense2vec\sense2vec\download.py", line 38, in <module>
    plac.call(main)
  File "C:\Users\rg\Anaconda2\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Users\rg\Anaconda2\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(_(args + varargs + extraopts), *_kwargs)
  File "c:\users\rg\src\sense2vec\sense2vec\download.py", line 20, in main
    sputnik.package(about.__title__, about.**version**, about.**default_model**)
AttributeError: 'module' object has no attribute '**title**'

Can you please help me?

**Comment by elyase** [comment]
Try:
```
sputnik --name sense2vec --repository-url http://index.spacy.io install reddit_vectors
```

**Comment by sevaader** [comment]
Yes it works with the sputnik command line. Thx

**Comment by sunwei317** [comment]
Run
 sputnik --name sense2vec --repository-url http://index.spacy.io install reddit_vectors
Traceback (most recent call last):
  File "/usr/local/bin/sputnik", line 11, in <module>
    load_entry_point('sputnik==0.9.3', 'console_scripts', 'sputnik')()
  File "/usr/local/lib/python2.7/site-packages/sputnik/__main__.py", line 12, in main
    args.run(args)
  File "/usr/local/lib/python2.7/site-packages/sputnik/cli.py", line 45, in run
    repository_url=args.repository_url)
  File "/usr/local/lib/python2.7/site-packages/sputnik/__init__.py", line 23, in install
    data_path = default_data_path(app_name)
  File "/usr/local/lib/python2.7/site-packages/sputnik/util.py", line 26, in default_data_path
    raise UnknownAppNameException(app_name)
sputnik.util.UnknownAppNameException: sense2vec

**Comment by qykqykqyk** [comment]
@sunwei317  Same Error... Have you found solutions. Thank so much.

**Comment by qykqykqyk** [comment]
@elyase  Do you have any hint for sunwei317's error? Thanks so much.

**Comment by jumbojett** [comment]
bump

**Comment by jumbojett** [comment]
This error occurs when I install with `USE_BLAS`

**Comment by patrickleet** [comment]
```
sputnik --name sense2vec --repository-url http://index.spacy.io install reddit_vectors
```
used to work in our docker image, but it's been a few months and now running it results in an error:

```
Traceback (most recent call last):
  File "/usr/local/bin/sputnik", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/sputnik/__main__.py", line 12, in main
    args.run(args)
  File "/usr/local/lib/python3.5/dist-packages/sputnik/cli.py", line 45, in run
    repository_url=args.repository_url)
  File "/usr/local/lib/python3.5/dist-packages/sputnik/__init__.py", line 44, in install
    archive = cache.fetch(package_name)
  File "/usr/local/lib/python3.5/dist-packages/sputnik/cache.py", line 67, in fetch
    checksum_header=util.s3_header('md5'))
  File "/usr/local/lib/python3.5/dist-packages/sputnik/uget.py", line 219, in download
    write_func=write)
  File "/usr/local/lib/python3.5/dist-packages/sputnik/uget.py", line 187, in read_request
    assert bytes_read == total_size
AssertionError
```

**Comment by xeb** [comment]
Bump. Running into this error as well.

```
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.5/site-packages/sputnik/util.py", line 24, in default_data_path
    mod = __import__(app_name, globals(), locals(), [], 0)
  File "/media/dropbox/Projects/sense2vec/sense2vec/__init__.py", line 2, in <module>
    from .vectors import VectorMap
ImportError: /media/dropbox/Projects/sense2vec/sense2vec/vectors.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/bin/sputnik", line 11, in <module>
    sys.exit(main())
  File "/home/user/anaconda3/lib/python3.5/site-packages/sputnik/__main__.py", line 12, in main
    args.run(args)
  File "/home/user/anaconda3/lib/python3.5/site-packages/sputnik/cli.py", line 45, in run
    repository_url=args.repository_url)
  File "/home/user/anaconda3/lib/python3.5/site-packages/sputnik/__init__.py", line 23, in install
    data_path = default_data_path(app_name)
  File "/home/user/anaconda3/lib/python3.5/site-packages/sputnik/util.py", line 26, in default_data_path
    raise UnknownAppNameException(app_name)
sputnik.util.UnknownAppNameException: sense2vec
```

**Comment by honnibal** [comment]
Should be fixed now --- we shouldn't need to use Sputnik anymore.

**Comment by MotorCityCobra** [comment]
Hello, anybody?  
I'm having trouble using the reddit vectors after downloading. I can't find them.  
After the vectors are downloaded I enter a '$locate reddit' and nothing relating to the vectors is located. Does something need to be unzipped and installed somewhere?

    $ sputnik --name sense2vec --repository-url http://index.spacy.io install reddit_vectors
    Continue downloading...
    Downloaded 560.90MB 100.00% 0.21MB/s eta 1s               
    archive.gz checksum/md5 OK
    INFO:sputnik.pool:install reddit_vectors-1.1.0
    $

If I enter  

    sputnik --name sense2vec --repository-url http://index.spacy.io install reddit_vectors  

into the command line again nothing happens.
