### ISSUE TITLE
Error compiling Cython file: Cython failed

### ISSUE THREAD

**Issue by spate141** [explosion/sense2vec#21]
- `pip install -r requirements.txt` : All requirements are satisfied

- `pip install -e .`

```
Obtaining file:///opt/sense2vec
Running setup.py (path:/opt/sense2vec/setup.py) egg_info for package from file:///opt/sense2vec


Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from libcpp.vector cimport vector
    from preshed.maps cimport PreshMap
    ^
    ------------------------------------------------------------
    
    vectors.pxd:2:0: 'preshed/maps.pxd' not found
    Processing sense2vec/vectors.pyx
    Traceback (most recent call last):
      File "/opt/sense2vec/bin/cythonize.py", line 199, in <module>
        main()
      File "/opt/sense2vec/bin/cythonize.py", line 195, in main
        find_process_files(root_dir)
      File "/opt/sense2vec/bin/cythonize.py", line 187, in find_process_files
        process(cur_dir, fromfile, tofile, function, hash_db)
      File "/opt/sense2vec/bin/cythonize.py", line 161, in process
        processor_function(fromfile, tofile)
      File "/opt/sense2vec/bin/cythonize.py", line 72, in process_pyx
        raise Exception('Cython failed')
    Exception: Cython failed
    Cythonizing sources
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/opt/sense2vec/setup.py", line 165, in <module>
        setup_package()
      File "/opt/sense2vec/setup.py", line 122, in setup_package
        generate_cython(root, src_path)
      File "/opt/sense2vec/setup.py", line 63, in generate_cython
        raise RuntimeError('Running cythonize failed')
    RuntimeError: Running cythonize failed
```

**Comment by vishalbelsare** [comment]
Did this issue see any resolution? Currently, I can't install sense2vec at all. Via pypi repository calls for downgrading spacy. Via the git repo the above cythonize error halts the install.

**Comment by spate141** [comment]
pip install -U cython solved the error!
