### ISSUE TITLE
Installation Problem ... 

### ISSUE THREAD

**Issue by jasonmaverick** [explosion/sense2vec#37]
That's the error I get:

C:\Python27>py -2.7 -m pip install -e git+git://github.com/spacy-io/sense2vec.gi
t#egg=sense2vec
Obtaining sense2vec from git+git://github.com/spacy-io/sense2vec.git#egg=sense2v
ec
  Updating c:\python27\src\sense2vec clone
    Complete output from command python setup.py egg_info:

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    from libcpp.vector cimport vector
    from preshed.maps cimport PreshMap
    ^
    ------------------------------------------------------------

    vectors.pxd:2:0: 'preshed\maps.pxd' not found
    Processing sense2vec\vectors.pyx
    Traceback (most recent call last):
      File "C:\Python27\src\sense2vec\bin\cythonize.py", line 199, in <module>
        main()
      File "C:\Python27\src\sense2vec\bin\cythonize.py", line 195, in main
        find_process_files(root_dir)
      File "C:\Python27\src\sense2vec\bin\cythonize.py", line 187, in find_proce
ss_files
        process(cur_dir, fromfile, tofile, function, hash_db)
      File "C:\Python27\src\sense2vec\bin\cythonize.py", line 161, in process
        processor_function(fromfile, tofile)
      File "C:\Python27\src\sense2vec\bin\cythonize.py", line 81, in process_pyx

        raise Exception('Cython failed')
    Exception: Cython failed
    Cythonizing sources
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Python27\src\sense2vec\setup.py", line 165, in <module>
        setup_package()
      File "C:\Python27\src\sense2vec\setup.py", line 122, in setup_package
        generate_cython(root, src_path)
      File "C:\Python27\src\sense2vec\setup.py", line 63, in generate_cython
        raise RuntimeError('Running cythonize failed')
    RuntimeError: Running cythonize failed

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Python27\src\s
ense2vec\

I have tried to install it with Python 3.6, but the same errors occur. I have tried many things, but nothing worked ... I'm sorry, I am not a programmer. I don't understand what the problem is.

Can you please help me?

**Comment by pres-nichols** [comment]
Try running the requirements.txt file again to check for error messages. In my case, I was missing Microsoft Visual C++. I downloaded it from [here](http://aka.ms/vcpython27) and the installation was successful.

**Comment by spnichol** [comment]
Try running the requirements.txt file again to check for error messages. In my case, I was missing Microsoft Visual C++. I downloaded it from [here ](http://aka.ms/vcpython27
)and the installation was successful

**Comment by honnibal** [comment]
Should be fixed now
