### ISSUE TITLE
I'm trying to work with the reddit_vectors. Can't find it after install.

### ISSUE THREAD

**Issue by MotorCityCobra** [explosion/sense2vec#50]
Hello, anybody?  
I'm having trouble using the reddit vectors after downloading. 
I've downloaded but I can't get the vectors to take in the example code.  

    >>> s2v = Sense2VecComponent('./anaconda3/envs/fastai/lib/python3.6/site-packages/sense2vec/data/reddit_vectors-1.1.0/vectors.bin')
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/eagle/anaconda3/envs/fastai/lib/python3.6/site-packages/sense2vec/__init__.py", line 32, in __init__
    self.s2v = load(vectors_path)
    File "/home/eagle/anaconda3/envs/fastai/lib/python3.6/site-packages/sense2vec/__init__.py", line 10, in load
    vector_map.load(vectors_path)
    File "vectors.pyx", line 208, in sense2vec.vectors.VectorMap.load
    File "vectors.pyx", line 306, in sense2vec.vectors.VectorStore.load
    File "cfile.pyx", line 13, in sense2vec.cfile.CFile.__init__
    OSError: Could not open binary file b'./anaconda3/envs/fastai/lib/python3.6/site-packages/sense2vec/data/reddit_vectors-1.1.0/vectors.bin/vectors.bin'

If I do a search for reddit vectors this is what I get.  

    $ locate reddit_vectors-1.1.0
    /home/eagle/anaconda3/envs/fastai/lib/python3.6/site-packages/sense2vec/data/reddit_vectors-1.1.0
    /home/eagle/anaconda3/envs/fastai/lib/python3.6/site-packages/sense2vec/data/__cache__/reddit_vectors-1.1.0
    /home/eagle/anaconda3/envs/fastai/lib/python3.6/site-packages/sense2vec/data/__cache__/reddit_vectors-1.1.0/archive.gz
    /home/eagle/anaconda3/envs/fastai/lib/python3.6/site-packages/sense2vec/data/__cache__/reddit_vectors-1.1.0/meta.json
    /home/eagle/anaconda3/envs/fastai/lib/python3.6/site-packages/sense2vec/data/reddit_vectors-1.1.0/freqs.json
    /home/eagle/anaconda3/envs/fastai/lib/python3.6/site-packages/sense2vec/data/reddit_vectors-1.1.0/meta.json
    /home/eagle/anaconda3/envs/fastai/lib/python3.6/site-packages/sense2vec/data/reddit_vectors-1.1.0/strings.json
    /home/eagle/anaconda3/envs/fastai/lib/python3.6/site-packages/sense2vec/data/reddit_vectors-1.1.0/vectors.bin

**Comment by MotorCityCobra** [comment]
I just didn't have the backslash at the end of the path.  

    s2v = Sense2VecComponent('/home/eagle/anaconda3/envs/fastai/lib/python3.6/site-packages/sense2vec/data/reddit_vectors-1.1.0/')
