### ISSUE TITLE
Using sense2vec with Spacy does not work 

### ISSUE THREAD

**Issue by Narquadah** [explosion/sense2vec#91]
Hey,

using the default example for spacy causes the following error. 

```py
import spacy
from sense2vec import Sense2VecComponent

nlp = spacy.load("en_core_web_sm")
s2v = Sense2VecComponent(nlp.vocab).from_disk("/path/to/s2v_reddit_2015_md")
nlp.add_pipe(s2v)

doc = nlp("A sentence about natural language processing.")
assert doc[3:6].text == "natural language processing"
freq = doc[3:6]._.s2v_freq
vector = doc[3:6]._.s2v_vec
most_similar = doc[3:6]._.s2v_most_similar(3)
```

```
Traceback (most recent call last):
  File "<input>", line 12, in <module>
  File "<path>/lib/python3.7/site-packages/spacy/tokens/underscore.py", line 38, in __getattr__
    return getter(self._obj)
  File "<path>/lib/python3.7/site-packages/sense2vec/component.py", line 145, in s2v_freq
    return obj.doc._._s2v.get_freq(self.s2v_key(obj))
  File "<path>/lib/python3.7/site-packages/sense2vec/component.py", line 155, in s2v_key
    obj.doc._._s2v.cfg["make_spacy_key"]
KeyError: 'make_spacy_key'
```

**Comment by ines** [comment]
Sorry, looks like there was a bug in the serialization / deserialization of the attributes and strings. Should be fixed in v1.0.2!
